# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  友链: /links
  关于: /about
#  开往: https://www.travellings.cn/go.html

# 是否显示目录
# 决定了是否在你的文章页面生成 Table of Contents（文章目录）。
# 默认抓取：只要你文章里用了 ## 或 ### 这种标题语法，目录就会自动出现。
# 即使你在全局 _config.yml 里设置了 TOC: false，
# 你依然可以在单篇文章的开头（Front-matter）里单独开启它。
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
  #Linux 服务器和某些 Hexo 插件对大小写非常敏感。
  - music/sakura-michi.mp3
  - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/cover.jpg
  - /img/welcome-cover.jpg

# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax MathJax 是一个用于在网页上显示数学公式的 JavaScript 库。
# MathJax 的脚本文件比较大。
mathjax: false

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值,前端显示用
local_search:
  # 是否启用
  enable: true
  path: search.xml

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  email: mailto:1368219312@qq.com
  facebook: https://www.facebook.com/profile.php?id=100021977747592
  #facebook_alt: https://www.facebook.com/gao.zebin.3
  twitter: https://x.com/zebin_gao
  github: https://github.com/ZebinGao
  instagram: https://www.instagram.com/nath.anann/
  #instagram_alt: https://www.instagram.com/zebin.gao/
  wechat: /img/wechat_code.png
  
# 备案
beian: 
  # 是否显示备案信息
  enable: false
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: false
  # 备案号
  beianInfo: 冀ICP备xxxxxxx号
  # 链接地址
  link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: true
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: 'Ov23liUMUoQLKTPswJDK'
  # 应用秘钥
  clientSecret: 'c46b751f5cbe796f506b01288d1c07f0446a45ef'
  # issue仓库名
  repo: 'blog-comments' # 你的仓库名
  # Github名
  owner: 'ZebinGao'         # 你的 GitHub 用户名
  # Github名
  admin: ['ZebinGao']      # 管理员列表，填你的用户名
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
# 告诉 Google、百度、Bing 等搜索引擎，你的网站主要是关于什么的。
keywords: Zebin, Blog, 编程, 生活, 技术

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: G-PWRM0QDS7E

# 网站ico
favicon: /img/favicon.png

# rss文件
# RSS 或 Atom 是一种内容同步协议。它像是一个“自动投递报纸”的服务：
# 对于你：你发布新文章后，Hexo 会自动把文章标题、链接和摘要更新到 atom.xml 这个文件里。
rss: atom.xml

# 要使用版权信息可以在这配置并设定许可方式，可以从 https://creativecommons.org/about/cclicenses/ 查询
copyright:
  enable: false
  license: "CC BY-NC-ND"
